### ISSUE TITLE
ZFS block device (zvol) performance is not good

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#178] opened 2016-06-06 19:01 UTC
Adding this purely for tracking purposes.  I have a 4x2 RAID10 of 7200RPM SAS NL drives.  Created a 1TB zvol, and exported it to vsphere.  Added a 64GB vdisk to a windows 7 VM and ran crystaldiskmark.  Created a 1TB "lun" with dd, exported that, and re-ran the test.  Keep in mind the esos box is connected by 10gb enet to the vsphere box.  Until this improves, I do not recommend using zvols.
![crystaldiskmark](https://cloud.githubusercontent.com/assets/2582198/15834058/829ecaa4-2bf7-11e6-90cb-aa90dd21138b.png)

**Comment by msmith626** [comment] 2016-06-06 19:24
So, did performance degrade with recent ESOS images, or is there your first
time testing ZFS volumes (performance)?

**Comment by dswartz** [comment] 2016-06-06 19:48
On 2016-06-06 15:24, Marc A. Smith wrote:
> So, did performance degrade with recent ESOS images, or is there your
> first
>  time testing ZFS volumes (performance)?

It isn't related to esos.  I was using file luns for quite awhile and 
decided to play with zvols.  Very ugly.  Not a new problem either...

**Comment by dswartz** [comment] 2016-06-07 01:10
A side note: if we're going to recommend going with vdisk_fileio using files in a dataset, the existing rc,d code which does '/usr/sbin/zpool import -c /etc/zfs/zpool.cache -aN' needs to change, as otherwise the lun files will not be accessible, and scst will bomb.  I suppose one could put entries in /etc/fstab and define a legacy mount for the dataset(s), but that's kinda ugly?

**Comment by msmith626** [comment] 2016-06-07 01:48
So, I'm learning more about ZFS, and I'm not sure I understand the specific
setup where you get bad performance.

For example:
- I create a ZFS storage pool.
- Next I create a ZFS volume on that storage pool.
- The ZFS volume is now available as a block device in Linux.
- Now in SCST I create a vdisk_blockio device using the ZFS volume from
above.
- Finally I map the SCST device as a LUN to a security group.

That gets bad performance? If so, why?

**Comment by dswartz** [comment] 2016-06-07 02:50
On 2016-06-06 21:48, Marc A. Smith wrote:
> So, I'm learning more about ZFS, and I'm not sure I understand the
> specific
>  setup where you get bad performance.
> 
>  For example:
>  - I create a ZFS storage pool.
>  - Next I create a ZFS volume on that storage pool.
>  - The ZFS volume is now available as a block device in Linux.
>  - Now in SCST I create a vdisk_blockio device using the ZFS volume
> from
>  above.
>  - Finally I map the SCST device as a LUN to a security group.
> 
>  That gets bad performance? If so, why?

If I knew that, I'd be the hero of the ZoL world :)  Joking aside, the 
zvol code in ZoL has not been as performant as in the original Open 
Solaris distros.  Still work in progress.  I was hoping it had improved 
in the last year, but apparently not.  Then again, last time I was 
serving up via 1gb, now 10gb, maybe that has affected things...

**Comment by msmith626** [comment] 2016-06-07 03:54
I haven't done any performance testing myself with it yet. I did some quick
searches and some people speak of performance problems with volumes, then
they tweak, and it sounds like they have it resolved in most cases (maybe
not 100%, but close).

I hope to do some testing in the next few weeks. I'll let you know how it
goes.


--Marc

**Comment by dswartz** [comment] 2016-06-24 13:57
This is very weird.  I tried to reproduce this and can't.  e.g. same exact scenario, and I get 800+MB/sec read and 500+MB/sec writes.

**Comment by msmith626** [comment] 2016-06-26 01:59
Hmm... so good performance with ZFS volumes -- what volume block size did you use? I almost have my lab setup, and I plan to spend a decent amount of time with ZFS... hopefully later this coming week.

--Marc

**Comment by dswartz** [comment] 2016-06-27 15:53
I used the default 8KB.

NAME          PROPERTY      VALUE     SOURCE
tank          volblocksize  -         -
tank/veeam    volblocksize  8K        -
tank/vsphere  volblocksize  8K        -

**Comment by dswartz** [comment] 2016-06-27 15:55
Make sure you select lz4 for compression.  The old one is lzjb which is legacy solaris.  Not as good.  I'm not sure if ZoL has defaulted to lz4 yet.  Also, if it's just a lab, you may want to set sync=disabled to avoid horrific write performance.  For a non-lab, you'd want to get one or more good SLOG recommended SSDs, but for a lab, it's not that essential, I don't think...

**Comment by msmith626** [comment] 2016-06-27 17:35
Why would I use compression? I want to test performance so I would think
compression or deduplication would always hinder performance. Is SLOG the
cache or log virtual device?

Marc

**Comment by dswartz** [comment] 2016-06-27 17:42
On 2016-06-27 13:35, Marc A. Smith wrote:
> Why would I use compression? I want to test performance so I would
> think
>  compression or deduplication would always hinder performance. Is SLOG
> the
>  cache or log virtual device?

Not sure what you mean?  lz4 compression is pretty close to zero 
overhead.  If you mean if would throw off measurement of the actual 
block devices, that's a valid point.

SLOG is Separate Log Device.  e.g. ZIL on separate devices, rather than 
on-pool blocks.

**Comment by msmith626** [comment] 2016-12-27 17:16
Hi,

Do you know if this is still actually an issue? I still haven't tested this personally myself. Is there any change upstream in recent ZFS versions? Or is this just known behavior with ZFS and we should expect lesser performance when using volumes?


--Marc

**Comment by msmith626** [comment] 2017-02-27 03:30
I'm closing this issue to clean up our open-list; I assume it still may be an issue with ZFS on Linux, either way we'll still have a record of it.

--Marc

**Closed by msmith626** 2017-02-27 03:30 UTC

**Comment by RubenKelevra** [comment] 2018-04-10 17:29
@msmith626 please reopen this, this is still a performance issue which should be resolvend:

Just an easy reproduction on my side. An SSD raid with an ext4 on it, I created a binary on it:

```
zfs create data /tanka.bin

dd if=/dev/zero of=/data/test.bin bs=1M count=1024K; rm /data/test.bin
# dd: Error while writing 'test.bin': No space left on device
# 97407475712 bytes (97 GB, 91 GiB) copied, 125,977 s, 773 MB/s

zfs create -V 70G data/disk1
dd if=/dev/zero of=/dev/zd0 bs=1M count=1024K # ctrl+c
# 5819596800 bytes (5,8 GB, 5,4 GiB) copied, 61,4706 s, 94,7 MB/s
zfs destroy data/disk1

zfs create -V 70G data/disk1
zfs set sync=disabled data/disk1
dd if=/dev/zero of=/dev/zd0 bs=1M count=1024K # ctrl+c
7908360192 bytes (7,9 GB, 7,4 GiB) copied, 80,5473 s, 98,2 MB/s
```

So linear writes with complete standard settings is one order of magnitude slower with ZVOLs than writing a binary to a ZFS pool.

And no, adding compression to this test doesn't make any sense.

**Comment by msmith626** [comment] 2018-04-10 20:49
I agree using the ZFS file system (mounted, using files) vs. ZFS volumes
may have a performance impact, however, this isn't anything specific to
ESOS itself (all ZoL would have the same issue).

But your example of outlining the difference is poor... with your high
throughput example, you're writing to a file on a file system (with ZFS and
the Linux page cache). In the poor performance example you're writing
directly to a block device (a ZFS volume). You'll likely always get better
performance numbers testing with this method when using a file system vs.
writing directly to a block device (eg, with XFS/BTRFS/EXT4/whatever you
would likely see performance gain when using the file system).

Please open an issue for the generic ZFS-volume-performance issue with the
ZoL project if you feel this behavior is not by design.



Marc A. Smith
Founder, CTO / Parodyne Inc.

// marc.smith@parodyne.com
// Mobile: 1-810-955-4735
// Office: 1-877-632-9004

// 4400 S. Saginaw St. Suite 1325
// Flint, MI 48507 USA
// www.parodyne.com

**Comment by RubenKelevra** [comment] 2018-04-11 11:55
Thanks for the fast response, I assume I just need to find the time to do a deep dive to this mechanics, I'm curious why this is so slow since there's no spinning disk involved and the raid controller have a very large write cache, the acknowledge should be very fast. :)

**Comment by msmith626** [comment] 2018-04-11 13:04
I agree, this does appear to be a problem. I haven't experimented
personally with all flash in a storage pool for ZFS, but I have used
spinning media for the pool and flash drives for the ZIL, and get decent
performance from volumes.

Have you experimented with different block sizes for the ZFS volume?

**Comment by dswartz** [comment] 2018-04-11 13:52
On 2018-04-11 09:04, Marc A. Smith wrote:
> I agree, this does appear to be a problem. I haven't experimented
> personally with all flash in a storage pool for ZFS, but I have used
> spinning media for the pool and flash drives for the ZIL, and get
> decent
> performance from volumes.
> 
> Have you experimented with different block sizes for the ZFS volume?

FWIW, there is an issue here (not ESOS fault).  I've seen personally 
(and also reported), doing writes to a zvol to have noticeably worse 
performance than to a file on a dataset.  Even in async mode.  It's 
something about the internals of zvols...
